(import ./helper :as t)
(import float-actions)

(t/test-start "grow-width: proposes larger floating width")
(def w (t/make-window 1 {:float true :w 400 :h 300}))
(def s (t/make-seat {:focused w}))
(def ctx (t/make-ctx {:windows @[w] :seats @[s]}))
(float-actions/grow-width ctx s)
(t/assert-eq (w :proposed-w) 450)
(t/assert-eq (w :proposed-h) 300)

(t/test-start "shrink-width: clamps to float minimum")
(def w (t/make-window 1 {:float true :w 90 :h 300}))
(def s (t/make-seat {:focused w}))
(def ctx (t/make-ctx {:windows @[w] :seats @[s]}))
(float-actions/shrink-width ctx s)
(t/assert-eq (w :proposed-w) 75)
(t/assert-eq (w :proposed-h) 300)

(t/test-start "grow-height: respects max height hint")
(def w (t/make-window 1 {:float true :w 400 :h 300 :max-h 325}))
(def s (t/make-seat {:focused w}))
(def ctx (t/make-ctx {:windows @[w] :seats @[s]}))
(float-actions/grow-height ctx s)
(t/assert-eq (w :proposed-w) 400)
(t/assert-eq (w :proposed-h) 325)

(t/test-start "pointer-move: uses pointer target")
(def focused (t/make-window 1 {:float true}))
(def target (t/make-window 2 {:float true}))
(def s (t/make-seat {:focused focused :pointer-target target}))
(def ctx (t/make-ctx {:windows @[focused target] :seats @[s]}))
(float-actions/pointer-move ctx s)
(t/assert-is (s :focused) target)
(t/assert-is (target :pointer-move-requested) s)

(t/test-start "pointer-resize: records requested edges")
(def w (t/make-window 1 {:float true}))
(def s (t/make-seat {:pointer-target w}))
(def ctx (t/make-ctx {:windows @[w] :seats @[s]}))
((float-actions/pointer-resize {:right true :bottom true}) ctx s)
(t/assert-is ((w :pointer-resize-requested) :seat) s)
(t/assert-truthy (get-in w [:pointer-resize-requested :edges :right]))
(t/assert-truthy (get-in w [:pointer-resize-requested :edges :bottom]))

(t/test-start "pointer-resize: works for tiled windows")
(def w (t/make-window 1 {:float false}))
(def s (t/make-seat {:pointer-target w}))
(def ctx (t/make-ctx {:windows @[w] :seats @[s]}))
((float-actions/pointer-resize {:right true}) ctx s)
(t/assert-is ((w :pointer-resize-requested) :seat) s)
(t/assert-truthy (get-in w [:pointer-resize-requested :edges :right]))

(t/report)
