(import ./helper :as t)
(import tree)

# --- Constructors ---

(t/test-start "leaf: creates leaf node")
(tree/reset-ids)
(def w @{:wid 1})
(def l (tree/leaf w 0.5))
(t/assert-eq (l :type) :leaf)
(t/assert-is (l :window) w)
(t/assert-eq (l :width) 0.5)
(t/assert-truthy (l :id) "has id")
(t/assert-eq (l :parent) nil)

(t/test-start "leaf: default width is 1.0")
(def l2 (tree/leaf @{:wid 2}))
(t/assert-eq (l2 :width) 1.0)

(t/test-start "container: creates with children and sets parent")
(tree/reset-ids)
(def w1 @{:wid 1})
(def w2 @{:wid 2})
(def l1 (tree/leaf w1))
(def l2 (tree/leaf w2))
(def c (tree/container :split :vertical @[l1 l2]))
(t/assert-eq (c :type) :container)
(t/assert-eq (c :mode) :split)
(t/assert-eq (c :orientation) :vertical)
(t/assert-eq (length (c :children)) 2)
(t/assert-is (l1 :parent) c)
(t/assert-is (l2 :parent) c)
(t/assert-eq (c :active) 0)
(t/assert-eq (c :width) 1.0)

(t/test-start "container: custom width")
(def c2 (tree/container :tabbed :horizontal @[] 0.66))
(t/assert-eq (c2 :width) 0.66)

# --- Predicates ---

(t/test-start "predicates")
(tree/reset-ids)
(def l (tree/leaf @{:wid 1}))
(def c (tree/container :split :vertical @[]))
(def tb (tree/container :tabbed :horizontal @[]))
(t/assert-truthy (tree/leaf? l))
(t/assert-falsey (tree/leaf? c))
(t/assert-truthy (tree/container? c))
(t/assert-falsey (tree/container? l))
(t/assert-truthy (tree/tabbed? tb))
(t/assert-falsey (tree/tabbed? c))
(t/assert-truthy (tree/split? c))
(t/assert-truthy (tree/root? l))
(def nested (tree/leaf @{:wid 2}))
(tree/append-child c nested)
(t/assert-falsey (tree/root? nested))

# --- Traversal ---

(t/test-start "first-leaf/last-leaf: flat container")
(tree/reset-ids)
(def w1 @{:wid 1})
(def w2 @{:wid 2})
(def w3 @{:wid 3})
(def l1 (tree/leaf w1))
(def l2 (tree/leaf w2))
(def l3 (tree/leaf w3))
(def c (tree/container :split :vertical @[l1 l2 l3]))
(t/assert-is (tree/first-leaf c) l1)
(t/assert-is (tree/last-leaf c) l3)

(t/test-start "first-leaf/last-leaf: nested")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def wc @{:wid 3})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def lc (tree/leaf wc))
(def inner (tree/container :split :horizontal @[lb lc]))
(def outer (tree/container :split :vertical @[la inner]))
(t/assert-is (tree/first-leaf outer) la)
(t/assert-is (tree/last-leaf outer) lc)

(t/test-start "first-leaf/last-leaf: tabbed uses active")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def tb (tree/container :tabbed :horizontal @[la lb]))
(t/assert-is (tree/first-leaf tb) la "active=0 -> first child")
(put tb :active 1)
(t/assert-is (tree/first-leaf tb) lb "active=1 -> second child")

(t/test-start "leaves: collects visible leaves")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def wc @{:wid 3})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def lc (tree/leaf wc))
(def inner (tree/container :split :vertical @[lb lc]))
(def outer (tree/container :split :horizontal @[la inner]))
(def result (tree/leaves outer))
(t/assert-eq (length result) 3)
(t/assert-is (result 0) la)
(t/assert-is (result 1) lb)
(t/assert-is (result 2) lc)

(t/test-start "leaves: tabbed only returns active")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def tb (tree/container :tabbed :horizontal @[la lb]))
(def result (tree/leaves tb))
(t/assert-eq (length result) 1)
(t/assert-is (result 0) la)

(t/test-start "all-leaves: includes inactive tabs")
(def result (tree/all-leaves tb))
(t/assert-eq (length result) 2)

(t/test-start "find-leaf: finds window in tree")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def wc @{:wid 3})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def lc (tree/leaf wc))
(def c (tree/container :split :vertical @[la lb lc]))
(t/assert-is (tree/find-leaf c wb) lb)
(t/assert-eq (tree/find-leaf c @{:wid 99}) nil)

(t/test-start "find-leaf: finds in nested tabbed (inactive)")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def tb (tree/container :tabbed :horizontal @[la lb]))
(t/assert-is (tree/find-leaf tb wb) lb)

(t/test-start "column-of: root returns self")
(tree/reset-ids)
(def l (tree/leaf @{:wid 1}))
(t/assert-is (tree/column-of l) l)

(t/test-start "column-of: nested returns root ancestor")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def c (tree/container :split :vertical @[la lb]))
(t/assert-is (tree/column-of la) c)
(t/assert-is (tree/column-of lb) c)

(t/test-start "child-index")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def c (tree/container :split :vertical @[la lb lc]))
(t/assert-eq (tree/child-index la) 0)
(t/assert-eq (tree/child-index lb) 1)
(t/assert-eq (tree/child-index lc) 2)
(t/assert-eq (tree/child-index c) nil "root has no parent")

# --- Mutations ---

(t/test-start "remove-child: removes and unlinks")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def c (tree/container :split :vertical @[la lb lc]))
(tree/remove-child lb)
(t/assert-eq (length (c :children)) 2)
(t/assert-is ((c :children) 0) la)
(t/assert-is ((c :children) 1) lc)
(t/assert-eq (lb :parent) nil)

(t/test-start "remove-child: clamps active")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def c (tree/container :tabbed :horizontal @[la lb]))
(put c :active 1)
(tree/remove-child lb)
(t/assert-eq (c :active) 0 "active clamped after removal")

(t/test-start "collapse-singles: single-child container collapses")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def c (tree/container :split :vertical @[la lb] 0.8))
(tree/remove-child la)
(def result (tree/collapse-singles c))
(t/assert-is result lb "collapsed to the remaining leaf")
(t/assert-eq (lb :width) 0.8 "inherited container width")
(t/assert-eq (lb :parent) nil "leaf is now root")

(t/test-start "collapse-singles: nested collapse")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def inner (tree/container :split :horizontal @[la lb]))
(def outer (tree/container :split :vertical @[inner] 0.5))
(tree/remove-child la)
(tree/collapse-singles inner)
(t/assert-eq (length (outer :children)) 1)
(def r2 (tree/collapse-singles outer))
(t/assert-is r2 lb "fully collapsed to leaf")
(t/assert-eq (lb :width) 0.5 "inherited outermost width")

(t/test-start "collapse-singles: no-op on multi-child")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def c (tree/container :split :vertical @[la lb]))
(def result (tree/collapse-singles c))
(t/assert-is result c "unchanged")

(t/test-start "insert-child: inserts at index")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def c (tree/container :split :vertical @[la lb]))
(tree/insert-child c 1 lc)
(t/assert-eq (length (c :children)) 3)
(t/assert-is ((c :children) 0) la)
(t/assert-is ((c :children) 1) lc)
(t/assert-is ((c :children) 2) lb)
(t/assert-is (lc :parent) c)

# --- Column operations ---

(t/test-start "insert-column/remove-column")
(tree/reset-ids)
(def l1 (tree/leaf @{:wid 1}))
(def l2 (tree/leaf @{:wid 2}))
(def l3 (tree/leaf @{:wid 3}))
(def cols @[l1 l2])
(tree/insert-column cols 1 l3)
(t/assert-eq (length cols) 3)
(t/assert-is (cols 1) l3)
(t/assert-eq (l3 :parent) nil)
(def removed (tree/remove-column cols 1))
(t/assert-is removed l3)
(t/assert-eq (length cols) 2)

(t/test-start "find-column-index")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def c (tree/container :split :vertical @[lb lc]))
(def cols @[la c])
(t/assert-eq (tree/find-column-index cols la) 0)
(t/assert-eq (tree/find-column-index cols lb) 1 "nested leaf finds its column")
(t/assert-eq (tree/find-column-index cols lc) 1)

# --- remove-leaf ---

(t/test-start "remove-leaf: top-level leaf")
(tree/reset-ids)
(def l1 (tree/leaf @{:wid 1}))
(def l2 (tree/leaf @{:wid 2}))
(def cols @[l1 l2])
(def [changed result] (tree/remove-leaf cols l1))
(t/assert-truthy changed "column was removed")
(t/assert-eq (length cols) 1)
(t/assert-is (cols 0) l2)

(t/test-start "remove-leaf: nested leaf collapses parent")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def c (tree/container :split :vertical @[la lb] 0.8))
(def cols @[c])
(def [changed result] (tree/remove-leaf cols la))
(t/assert-falsey changed "column not removed, just collapsed")
(t/assert-is result lb "collapsed to remaining leaf")
(t/assert-is (cols 0) lb "column updated")
(t/assert-eq (lb :width) 0.8 "inherited width")

(t/test-start "remove-leaf: from 3-child container no collapse")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def c (tree/container :split :vertical @[la lb lc]))
(def cols @[c])
(def [changed result] (tree/remove-leaf cols lb))
(t/assert-falsey changed)
(t/assert-eq (length (c :children)) 2)
(t/assert-is ((c :children) 0) la)
(t/assert-is ((c :children) 1) lc)

# --- wrap-in-container ---

(t/test-start "wrap-in-container: top-level leaf")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1} 0.8))
(def lb (tree/leaf @{:wid 2}))
(def cols @[la])
(def c (tree/wrap-in-container cols la :split :vertical lb :after))
(t/assert-is (cols 0) c "column replaced with container")
(t/assert-eq (c :width) 0.8 "inherited width")
(t/assert-eq (length (c :children)) 2)
(t/assert-is ((c :children) 0) la)
(t/assert-is ((c :children) 1) lb)
(t/assert-is (la :parent) c)
(t/assert-is (lb :parent) c)

(t/test-start "wrap-in-container: sibling-pos :before")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def cols @[la])
(def c (tree/wrap-in-container cols la :split :vertical lb :before))
(t/assert-is ((c :children) 0) lb "sibling comes first")
(t/assert-is ((c :children) 1) la)

(t/test-start "wrap-in-container: nested node")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def wc @{:wid 3})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def lc (tree/leaf wc))
(def outer (tree/container :split :vertical @[la lb]))
(def cols @[outer])
(def c (tree/wrap-in-container cols lb :split :horizontal lc :after))
(t/assert-eq (length (outer :children)) 2)
(t/assert-is ((outer :children) 0) la)
(t/assert-is ((outer :children) 1) c)
(t/assert-is (c :parent) outer)
(t/assert-eq (length (c :children)) 2)
(t/assert-is ((c :children) 0) lb)
(t/assert-is ((c :children) 1) lc)

# --- update-active-path ---

(t/test-start "update-active-path: sets active indices up the tree")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def inner (tree/container :split :horizontal @[lb lc]))
(def outer (tree/container :split :vertical @[la inner]))
(tree/update-active-path lc)
(t/assert-eq (inner :active) 1 "inner active points to lc")
(t/assert-eq (outer :active) 1 "outer active points to inner")

# --- next/prev leaf in columns ---

(t/test-start "next-leaf-in-columns: walks across columns")
(tree/reset-ids)
(def wa @{:wid 1})
(def wb @{:wid 2})
(def wc @{:wid 3})
(def la (tree/leaf wa))
(def lb (tree/leaf wb))
(def lc (tree/leaf wc))
(def c (tree/container :split :vertical @[lb lc]))
(def cols @[la c])
(t/assert-is (tree/next-leaf-in-columns cols la) lb)
(t/assert-is (tree/next-leaf-in-columns cols lb) lc)
(t/assert-eq (tree/next-leaf-in-columns cols lc) nil "end of columns")

(t/test-start "prev-leaf-in-columns")
(t/assert-is (tree/prev-leaf-in-columns cols lc) lb)
(t/assert-is (tree/prev-leaf-in-columns cols lb) la)
(t/assert-eq (tree/prev-leaf-in-columns cols la) nil "start of columns")

# --- focus-successor ---

(t/test-start "focus-successor: after removing from container")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def lc (tree/leaf @{:wid 3}))
(def c (tree/container :split :vertical @[la lb lc]))
(def cols @[c])
(tree/remove-child lb)
(def succ (tree/focus-successor cols 0 1 c))
(t/assert-is succ lc "focuses next sibling")

(t/test-start "focus-successor: removing last child focuses prev")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def c (tree/container :split :vertical @[la lb]))
(def cols @[c])
(tree/remove-child lb)
(def succ (tree/focus-successor cols 0 1 c))
(t/assert-is succ la "focuses remaining sibling")

(t/test-start "focus-successor: column removed, focuses adjacent")
(tree/reset-ids)
(def la (tree/leaf @{:wid 1}))
(def lb (tree/leaf @{:wid 2}))
(def cols @[lb])
(def succ (tree/focus-successor cols 0 0 nil))
(t/assert-is succ lb "focuses adjacent column")

(t/test-start "focus-successor: no columns left")
(def cols @[])
(def succ (tree/focus-successor cols 0 0 nil))
(t/assert-eq succ nil)

(t/report)
